[program:demo_zipride_tasks]
command=/var/deployments/demo/zipride/.venv/bin/celery -A settings worker -n demo-zipride@%%h -l INFO --autoscale=10,3
directory=/var/deployments/demo/zipride
stderr_logfile=/var/deployments/demo/zipride/logs/tasks.stderr.log
stdout_logfile=/var/deployments/demo/zipride/logs/tasks.stdout.log
autostart=true
autorestart=true
user=ubuntu
environment=HOME="/home/ubuntu",USER="ubuntu"
