#!/bin/bash
set -e

update_app()
{
    cd /var/deployments/demo/zipride
    git pull
    source env/bin/activate
    pip install -r requirements.txt
    python manage.py migrate
    python manage.py collectstatic --noinput
    sudo supervisorctl restart demo_zipride_app:* demo_zipride_beat demo_zipride_tasks
}

update_app
