# Generated by Django 6.0.4 on 2026-05-13 20:45

import app.core.users.utils
import app.mixins.models
import app.utils.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sessions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Verification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "session_key",
                    app.utils.fields.CharField(db_index=True, max_length=40, unique=True),
                ),
                (
                    "permyt_user_id",
                    app.utils.fields.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    app.utils.fields.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scanned", "Scanned"),
                            ("awaiting", "Awaiting approval"),
                            ("verifying", "Verifying"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("min_age", app.utils.fields.PositiveSmallIntegerField(default=18)),
                ("is_older", app.utils.fields.BooleanField(blank=True, null=True)),
                (
                    "request_id",
                    app.utils.fields.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "failure_reason",
                    app.utils.fields.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(app.core.users.utils.set_delete_user),
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(app.core.users.utils.set_delete_user),
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_by",),
                "abstract": False,
            },
            bases=(
                app.mixins.models.BulkActionsMixin,
                app.mixins.models.PermissionsMixin,
                app.mixins.models.SubModulesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="LoginToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("token", app.utils.fields.CharField(max_length=2048, unique=True)),
                ("scanned", app.utils.fields.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(app.core.users.utils.set_delete_user),
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    app.utils.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_tokens",
                        to="sessions.session",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(app.core.users.utils.set_delete_user),
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verification",
                    app.utils.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_tokens",
                        to="verifications.verification",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_by",),
                "abstract": False,
            },
            bases=(
                app.mixins.models.BulkActionsMixin,
                app.mixins.models.PermissionsMixin,
                app.mixins.models.SubModulesMixin,
                models.Model,
            ),
        ),
    ]
