# Generated by Django 6.0.3 on 2026-04-17 21:03

import app.core.users.utils
import app.mixins.models
import app.utils.encoders
import app.utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TstMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "data",
                    app.utils.fields.JSONField(
                        blank=True, default=dict, encoder=app.utils.encoders.JSONEncoder
                    ),
                ),
                ("message", app.utils.fields.CharField(blank=True, max_length=256, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(app.core.users.utils.set_delete_user),
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(app.core.users.utils.set_delete_user),
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                app.mixins.models.BulkActionsMixin,
                app.mixins.models.PermissionsMixin,
                app.mixins.models.SubModulesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="TstModelA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "data",
                    app.utils.fields.JSONField(
                        blank=True, default=dict, encoder=app.utils.encoders.JSONEncoder
                    ),
                ),
                ("message", app.utils.fields.CharField(blank=True, max_length=256, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(app.core.users.utils.set_delete_user),
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(app.core.users.utils.set_delete_user),
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                app.mixins.models.BulkActionsMixin,
                app.mixins.models.PermissionsMixin,
                app.mixins.models.SubModulesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="TstModelB",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "data",
                    app.utils.fields.JSONField(
                        blank=True, default=dict, encoder=app.utils.encoders.JSONEncoder
                    ),
                ),
                ("message", app.utils.fields.CharField(blank=True, max_length=256, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(app.core.users.utils.set_delete_user),
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(app.core.users.utils.set_delete_user),
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                app.mixins.models.BulkActionsMixin,
                app.mixins.models.PermissionsMixin,
                app.mixins.models.SubModulesMixin,
                models.Model,
            ),
        ),
    ]
