[fcgi-program:demo_bank_app]
socket=tcp://localhost:9013
command=/var/deployments/demo/bank/env/bin/daphne -u /var/deployments/demo/bank/sockets/app.%(process_num)s.sock --fd 0 settings.asgi:application
directory=/var/deployments/demo/bank
stderr_logfile=/var/deployments/demo/bank/logs/app.stderr.log
stdout_logfile=/var/deployments/demo/bank/logs/app.stdout.log
autostart=true
autorestart=true
user=ubuntu
environment=HOME="/home/ubuntu",USER="ubuntu"
numprocs=2
process_name=%(program_name)s_%(process_num)s
