[program:demo_bank_beat]
command=/var/deployments/demo/bank/.venv/bin/celery -A settings beat -l INFO
directory=/var/deployments/demo/bank
stderr_logfile=/var/deployments/demo/bank/logs/beat.stderr.log
stdout_logfile=/var/deployments/demo/bank/logs/beat.stdout.log
autostart=true
autorestart=true
user=ubuntu
environment=HOME="/home/ubuntu",USER="ubuntu"
