[program:demo_bank_tasks]
command=/var/deployments/demo/bank/.venv/bin/celery -A settings worker -n demo-bank@%%h -l INFO --autoscale=10,3
directory=/var/deployments/demo/bank
stderr_logfile=/var/deployments/demo/bank/logs/tasks.stderr.log
stdout_logfile=/var/deployments/demo/bank/logs/tasks.stdout.log
autostart=true
autorestart=true
user=ubuntu
environment=HOME="/home/ubuntu",USER="ubuntu"
