#!/bin/bash
set -e

update_app()
{
    cd /var/deployments/demo/bank
    git pull
    source env/bin/activate
    pip install -r requirements.txt
    python manage.py migrate
    python manage.py update_scope
    python manage.py collectstatic --no-input
    sudo supervisorctl restart demo_bank_app:* demo_bank_beat demo_bank_tasks
}

update_app
