[program:demo_stripe_beat]
command=/var/deployments/demo/stripe/.venv/bin/celery -A settings beat -l INFO
directory=/var/deployments/demo/stripe
stderr_logfile=/var/deployments/demo/stripe/logs/beat.stderr.log
stdout_logfile=/var/deployments/demo/stripe/logs/beat.stdout.log
autostart=true
autorestart=true
user=ubuntu
environment=HOME="/home/ubuntu",USER="ubuntu"
