upstream demo_stripe {
  server localhost:9016;
}

server {
  listen 443 ssl;
  listen [::]:443 ssl;
  server_name stripe.permyt.io;

  ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
  ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

  access_log /var/deployments/demo/stripe/logs/nginx.access.log;
  error_log /var/deployments/demo/stripe/logs/nginx.error.log;

  client_max_body_size 10M;

  # For Django managed static files (generated via collectstattic)
  location /static {
    alias   /var/deployments/demo/stripe/static;
    autoindex off;

    expires 30d;
    add_header Pragma public;
    add_header Cache-Control "public, must-revalidate, proxy-revalidate";

    # Enable gzip static files (js, css, misc): now enabled by the "gzip_settings.conf"
    gzip_static on;
  }

  location / {
    proxy_pass http://demo_stripe;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto  $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
