#!/bin/bash
set -e

update_app()
{
    cd /var/deployments/demo/stripe
    git pull
    source env/bin/activate
    pip install -r requirements.txt
    python manage.py migrate
    python manage.py collectstatic --noinput
    sudo supervisorctl restart demo_stripe_app:* demo_stripe_beat demo_stripe_tasks
}

update_app
