# Generated by Django 6.0.4 on 2026-06-29 14:38

import app.utils.fields
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sessions", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="birthdate",
        ),
        migrations.RemoveField(
            model_name="user",
            name="country",
        ),
        migrations.RemoveField(
            model_name="user",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="user",
            name="tax_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="vat",
        ),
        migrations.AddField(
            model_name="logintoken",
            name="error",
            field=app.utils.fields.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="adverse_media",
            field=app.utils.fields.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="pep",
            field=app.utils.fields.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="sanctions_match",
            field=app.utils.fields.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="self_excluded",
            field=app.utils.fields.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="logintoken",
            name="session",
            field=app.utils.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login_tokens",
                to="sessions.session",
            ),
        ),
    ]
