# Generated by Django 6.0.4 on 2026-05-13 20:45

import app.core.users.utils
import app.mixins.models
import app.utils.encoders
import app.utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("action", app.utils.fields.CharField(max_length=32)),
                (
                    "data",
                    app.utils.fields.EncryptedJSONField(
                        blank=True, default=dict, encoder=app.utils.encoders.JSONEncoder
                    ),
                ),
                ("success", app.utils.fields.BooleanField(default=True)),
                (
                    "permyt_request_id",
                    app.utils.fields.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(app.core.users.utils.set_delete_user),
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(app.core.users.utils.set_delete_user),
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
            bases=(
                app.mixins.models.BulkActionsMixin,
                app.mixins.models.PermissionsMixin,
                app.mixins.models.SubModulesMixin,
                models.Model,
            ),
        ),
    ]
