# Generated by Django 6.0.4 on 2026-05-13 20:45

import app.utils.fields
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("logs", "0001_initial"),
        ("verifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="verification",
            field=app.utils.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs",
                to="verifications.verification",
            ),
        ),
    ]
