[program:demo_sentinel_tasks]
command=/var/deployments/demo/sentinel/.venv/bin/celery -A settings worker -n demo-sentinel@%%h -l INFO --autoscale=10,3
directory=/var/deployments/demo/sentinel
stderr_logfile=/var/deployments/demo/sentinel/logs/tasks.stderr.log
stdout_logfile=/var/deployments/demo/sentinel/logs/tasks.stdout.log
autostart=true
autorestart=true
user=ubuntu
environment=HOME="/home/ubuntu",USER="ubuntu"
