#!/bin/bash
set -e

update_app()
{
    cd /var/deployments/demo/sentinel
    git pull
    source env/bin/activate
    pip install -r requirements.txt
    python manage.py migrate
    python manage.py update_scope
    python manage.py collectstatic --no-input
    sudo supervisorctl restart demo_sentinel_app:* demo_sentinel_beat demo_sentinel_tasks
}

update_app
