import shutil

from typing import Any, Sequence, Type
from uuid import uuid4

from django.conf import settings
from django.db.models import TextChoices

import pytest
from factory.django import DjangoModelFactory

from app.core.users.factories import User, UserFactory
from app.managers import OwnerManager, PublicReadManager, SuperuserManager
from app.mixins.models import AppModel
from app.mixins.viewsets import AppModelViewSet
from app.serializers import AppModelSerializer
from app.utils.middleware import SetCurrentUser
from app.utils.tests import AppTestClient
from app.utils.views import FakeRequest

__all__ = ("ModelTest",)


@pytest.mark.django_db(databases="__all__")
class ModelTest:
    """
    Automated tests to be used on all models.

    This test check if model, manager, serializer and viewset
    are proper defined with the correct permissions. These
    tests reduce significantly the probability of typos and
    security issues.
    """

    # Model, factory and endpoint that is being tested
    model: Type[AppModel] = None
    factory: DjangoModelFactory = None
    endpoint: str = None

    # Every model should use one of this permissions types.
    class PermissionType(TextChoices):
        SUPERUSER = "superuser", "Superuser content"
        PUBLIC_READ = "public_read", "Content readable by anyone"
        OWNER = "owner", "Content belonging to an user"

    PERMISSION_TYPES = PermissionType

    # Superuser field
    SUPERUSER_FIELD: str = "is_superuser"

    # Define what type of permission (defined above) this model should have
    # By default, the model will use SUPERUSER permissions
    PERMISSION_TYPE = None

    # If everyone can read the content
    PERMISSION_PUBLIC = False

    # Tests will be executed against this set of permissions
    # This is autogenerated by `setup_method` based on previous settings
    PERMISSIONS: dict[str, tuple[bool]] = {}

    # Making sure Serializer permissions are the expected one
    SERIALIZER_READ_PERMISSIONS: Sequence[str] = None
    SERIALIZER_WRITE_PERMISSIONS: Sequence[str] = None
    SERIALIZER_ADMIN_PERMISSIONS: Sequence[str] = None
    SERIALIZER_READ_ONLY_FIELDS: Sequence[str] = None
    SERIALIZER_IMMUTABLE_FIELDS: Sequence[str] = None
    SERIALIZER_HIDDEN_FIELDS: Sequence[str] = None

    # Expected managers based on PERMISSION_TYPES
    MANAGERS = {
        PERMISSION_TYPES.SUPERUSER: SuperuserManager,
        PERMISSION_TYPES.PUBLIC_READ: PublicReadManager,
        PERMISSION_TYPES.OWNER: OwnerManager,
    }

    # Expected codes based on user permission
    CODES_BY_PERMISSION = {
        True: AppTestClient.ACCEPTED,
        False: AppTestClient.DECLINED,
    }

    # Expected queries
    QUERIES_LIST: int = None
    QUERIES_GET: int = None
    QUERIES_UPDATE: int = None
    QUERIES_CREATE: int = None
    QUERIES_DELETE: int = None

    # Enable/Disable views
    ENABLE_VIEWS: bool = True
    CAN_ANY_CREATE: bool = False  # For accounts, any user can create these objects
    CAN_CREATE: bool = True  # If True, users with write permissions can create objects
    CAN_DELETE: bool = True  # If True, users with write permissions can delete objects
    ALLOW_GUESTS: bool = False

    # Fixed number of objects
    OBJS_LIST: int = None

    @property
    def name(self):
        """Shortcut to print test name during assertion errors"""
        return self.__class__.__name__

    @classmethod
    def setup_class(cls, *args, **kwargs):
        """
        Checks if test, model and manager are setup properly.
        """

        # Check if model and factory have been defined in the test
        assert cls.model, f"{cls.__name__} does not have `model` defined."
        assert cls.factory, f"{cls.__name__} does not have `factory` defined."
        assert (
            cls.model == cls.factory._meta.model
        ), f"`model` and `factory.Meta.model` does not match in {cls.__name__}"

        # Check if test class is using the correct name
        assert (
            cls.__name__.replace("Test", "") == cls.model.__name__
        ), f"Test class name does not match model name. It should be `Test{cls.model.__name__}`."

        if cls.ENABLE_VIEWS:
            # Check if model have a serializer and it is properly configured
            try:
                serializer = cls.model.get_serializer_class()
                assert issubclass(
                    serializer, AppModelSerializer
                ), f"{serializer.__name__} must be a subclass of AppModelSerializer"
                assert cls.model == serializer.get_meta_field(
                    "model"
                ), f"`model` and `serializer.Meta.model` does not match in {cls.__name__}"
            except (ImportError, AttributeError) as exc:
                package = ".".join(cls.__module__.split(".")[:-1])
                path = package + f".serializers.{cls.model.__name__}Serializer"
                raise NotImplementedError(f"{path} has not been implemented.") from exc

            # Check if model have a viewset and it is properly configured
            try:
                viewset = cls.model.get_viewset_class()
                assert issubclass(
                    viewset, AppModelViewSet
                ), f"{viewset.__name__} must be a subclass of AppModelViewSet"
                assert (
                    cls.model == viewset.model
                ), f"`model` and `viewset.Meta.model` does not match in {cls.__name__}"
            except (ImportError, AttributeError) as exc:
                package = ".".join(cls.__module__.split(".")[:-1])
                path = package + f".views.{cls.model.__name__}ViewSet"
                raise NotImplementedError(f"{path} has not been implemented.") from exc

            # Making sure endpoint exists and starts and ends with a `/`
            assert cls.endpoint, f"{cls.__name__} does not have `endpoint` defined."
            cls.endpoint = cls.endpoint if cls.endpoint.startswith("/") else f"/{cls.endpoint}"
            cls.endpoint = cls.endpoint if cls.endpoint.endswith("/") else f"{cls.endpoint}/"

        # Check if permission type have been defined in the test
        assert cls.PERMISSION_TYPE, f"{cls.__name__} does not have `PERMISSION_TYPE` defined."

        # Check if model contains the expected manager for is PERMISSION_TYPE
        assert isinstance(
            cls.model.objects, cls.MANAGERS[cls.PERMISSION_TYPE]
        ), "Model is not using the correct manager"

        # Expected permissions for SUPERUSER content
        # The tuple represents ('can_read', 'can_write', 'can_create', 'can_delete')
        if cls.PERMISSION_TYPE == cls.PERMISSION_TYPES.SUPERUSER:
            cls.PERMISSIONS = {
                "unauthenticated": (
                    cls.ALLOW_GUESTS and cls.PERMISSION_PUBLIC,
                    False,
                    False,
                    False,
                ),
                "guest": (cls.PERMISSION_PUBLIC, False, False, False),
                "creator": (cls.PERMISSION_PUBLIC, False, False, False),
                "superuser": (True, True, cls.CAN_CREATE, cls.CAN_DELETE),
            }

        # Expected permissions for OWNER content
        # The tuple represents ('can_read', 'can_write', 'can_create')
        if cls.PERMISSION_TYPE == cls.PERMISSION_TYPES.OWNER:
            cls.PERMISSIONS = {
                "unauthenticated": (
                    cls.ALLOW_GUESTS and cls.PERMISSION_PUBLIC,
                    False,
                    False,
                    False,
                ),
                "guest": (cls.PERMISSION_PUBLIC, False, False, False),
                "creator": (True, True, cls.CAN_CREATE, cls.CAN_DELETE),
                "superuser": (True, True, cls.CAN_CREATE, cls.CAN_DELETE),
            }

        # Expected permissions for PUBLIC_READ content
        # The tuple represents ('can_read', 'can_write', 'can_create', 'can_delete')
        if cls.PERMISSION_TYPE == cls.PERMISSION_TYPES.PUBLIC_READ:
            cls.PERMISSIONS = {
                "unauthenticated": (cls.ALLOW_GUESTS, False, False, False),
                "guest": (True, False, False, False),
                "creator": (True, False, False, False),
                "superuser": (True, True, cls.CAN_CREATE, cls.CAN_DELETE),
            }

        assert (
            getattr(cls.model.objects, "_allow_guests", False) == cls.ALLOW_GUESTS
        ), f"Model manager `_allow_guests` does not match `{cls.__name__}.ALLOW_GUESTS`"

    @classmethod
    def teardown_class(cls, *args, **kwargs):
        """
        Clean up after all tests have been executed.
        """
        # Delete uploaded files
        shutil.rmtree(settings.MEDIA_ROOT, ignore_errors=True)

    def _create_users(self, objs: Sequence[AppModel]) -> dict[str, User]:
        """
        Create users to test specif object.

        :param obj: Object to create users for.
        :return: A dict of users by type an list of user that should match that type
        """

        for obj in objs:
            # pylint: disable=isinstance-second-argument-not-valid-type
            assert isinstance(obj, self.model), "Object is not an instance of the model."

        obj = objs[0]
        _uuid = uuid4().hex[:8]

        # Common Users: All types of permissions have these types.
        # They are the only available for SUPERUSER permissions.
        users = {
            "unauthenticated": None,
            "guest": UserFactory.create(username=f"guest_{_uuid}"),
            "superuser": UserFactory(
                **{"username": f"superuser_{_uuid}", self.SUPERUSER_FIELD: True}
            ),
            "creator": obj.get_creator(),
        }

        return users

    def _get_object(self, number: bool = 1, commit: bool = True, user=None, **kwargs):
        """
        Return an object or batch of objects.
        """
        # Create objects with a new user
        user = user or UserFactory.create()
        if self.PERMISSION_TYPE == self.PERMISSION_TYPES.OWNER and self.model != User:
            field = getattr(self.model.objects, "_field", "created_by")
            is_id = field.endswith("_id")
            kwargs.setdefault(field, user.id if is_id else user)

        with SetCurrentUser(user):
            action = "create_batch" if commit else "build_batch"
            objs = getattr(self.factory, action)(number, **kwargs)
        return objs[0] if number == 1 else objs

    def _clean_data(self, data: dict[str, Any]):
        """
        Remove unwanted fields from data
        """
        if data and "file" in data:
            del data["file"]
        return data

    @pytest.mark.permissions
    def test_model_permissions(self):
        """
        Test if model is applying the correct permissions to users.
        """
        owner = UserFactory.create()
        obj = self._get_object(user=owner)
        users = self._create_users([obj])

        # For each user, check if permission as member, admin and owner
        # correspond to the expected permissions declared in PERMISSIONS const.
        for user_type, user in users.items():
            if user is None:
                continue  # unauthenticated access is enforced at the viewset layer
            assert (
                obj.can_read(user) == self.PERMISSIONS[user_type][0]
            ), f"Incorrect permission as reader for `{user_type}`"
            assert (
                obj.can_write(user) == self.PERMISSIONS[user_type][1]
            ), f"Incorrect permission as writer for `{user_type}`"

    @pytest.mark.permissions
    def test_manager_permissions(self):
        """
        Test if manager is applying the correct permissions to users.
        """
        owner = UserFactory.create()
        obj = self._get_object(user=owner)
        users = self._create_users([obj])

        # For each user, check if permission as member, admin and owner
        # correspond to the expected permissions declared in PERMISSIONS const.
        for user_type, user in users.items():
            if user is None:
                continue  # unauthenticated access is enforced at the viewset layer
            objects = self.model.objects.as_reader(user, as_superuser=True).filter(pk=obj.pk)
            assert (
                objects.exists() == self.PERMISSIONS[user_type][0]
            ), f"Incorrect permission as reader for `{user_type}`"

            objects = self.model.objects.as_writer(user, as_superuser=True).filter(pk=obj.pk)
            assert (
                objects.exists() == self.PERMISSIONS[user_type][1]
            ), f"Incorrect permission as writer for `{user_type}`"

    @pytest.mark.permissions
    def test_serializer_permissions(self):
        """
        Test if serializer is applying the correct permissions to users.
        """
        # No need to test if views are disabled
        if not self.ENABLE_VIEWS:
            return

        serializer_class = self.model.get_serializer_class()

        # Check if serializer read_permissions
        # match the ones declared on the test
        assert set(self.SERIALIZER_READ_PERMISSIONS or []) == set(
            serializer_class.get_meta_field("read_permissions", default=[])
        ), (
            f"Permissions in {self.name}.SERIALIZER_READ_PERMISSIONS and "
            "{serializer_class.__name__}.read_permissions don't match."
        )

        # Check if serializer write_permissions
        # match the ones declared on the test
        assert set(self.SERIALIZER_WRITE_PERMISSIONS or []) == set(
            serializer_class.get_meta_field("write_permissions", default=[])
        ), (
            f"Permissions in {self.name}.SERIALIZER_WRITE_PERMISSIONS and "
            "{serializer_class.__name__}.write_permissions don't match."
        )

        # Check if serializer admin_permissions
        # match the ones declared on the test
        assert set(self.SERIALIZER_ADMIN_PERMISSIONS or []) == set(
            serializer_class.get_meta_field("admin_permissions", default=[])
        ), (
            f"Permissions in {self.name}.SERIALIZER_ADMIN_PERMISSIONS and "
            "{serializer_class.__name__}.admin_permissions don't match."
        )

        # Check if serializer is forcing read_only_fields
        assert set(self.SERIALIZER_READ_ONLY_FIELDS or []) == set(
            serializer_class.get_meta_field("read_only_fields", default=[])
        ), (
            f"Fields in {self.name}.SERIALIZER_READ_ONLY_FIELDS and "
            f"{serializer_class.__name__}.read_only_fields don't match."
        )

        # Check if serializer is forcing immutable_fields
        assert set(self.SERIALIZER_IMMUTABLE_FIELDS or []) == set(
            serializer_class.get_meta_field("immutable_fields", default=[])
        ), (
            f"Fields in {self.name}.SERIALIZER_IMMUTABLE_FIELDS and "
            f"{serializer_class.__name__}.immutable_fields don't match."
        )

        # Make sure hidden fields are not in the serializer fields
        hidden_fields = set(self.SERIALIZER_HIDDEN_FIELDS or [])
        serializer_fields = set(serializer_class.get_meta_field("fields", default=[]))
        for hidden_field in hidden_fields:
            assert (
                hidden_field not in serializer_fields
            ), f"Field `{hidden_field}` is declared as hidden but is present in the serializer fields."

        # Check if serializer.validate are still validating fields permissions
        superuser = UserFactory(**{self.SUPERUSER_FIELD: True})
        with SetCurrentUser(superuser):
            obj = self._get_object()
            serializer = serializer_class(
                obj, data={}, partial=True, context={"request": FakeRequest(superuser)}
            )
            serializer.is_valid(raise_exception=True)
            assert getattr(serializer, "_permissions_validated", False), (
                "Cannot verify `read_permissions` and `write_permissions` "
                f"on `{serializer_class.__name__}`. Check if `validate` method "
                "was overridden and `super().validate(attrs)` was not added."
            )

    # pylint: disable=too-many-branches
    @pytest.mark.permissions
    @pytest.mark.viewsets
    def test_viewset_permissions(self, client, django_assert_max_num_queries):
        """
        Test if viewset is applying the correct permissions to users.
        """
        # No need to test if views are disabled
        if not self.ENABLE_VIEWS:
            return

        # Create objects to check if total number of queries
        # does not grow with number of objects. If that is the case
        # select_related or prefetch_related is needed in the serializer
        total_objects = 50
        existing_objects = total_objects  # Track how many objects have been deleted
        objs = self._get_object(number=total_objects)
        users = self._create_users(objs)
        obj_data = None

        # LIST: Check permissions to who can fetch objects (list)
        # ---------------------------------------------------------------------

        for user_type, user in users.items():
            with AppTestClient(locals(), user=user) as tc:
                has_permission = self.PERMISSIONS[user_type][0]
                list_expected_codes = (
                    self.CODES_BY_PERMISSION[has_permission]
                    if user is None
                    else AppTestClient.ACCEPTED
                )
                response = tc.get(
                    f"{self.endpoint}",
                    query_params={"as_superuser": True},
                    expected_codes=list_expected_codes,
                    max_queries=self.QUERIES_LIST,
                )
                if user is None and not has_permission:
                    continue
                n_objects = len(response.data.get("results"))
                # Some extra objects might have been created in the process
                expected_with_permission = (
                    n_objects >= total_objects
                    if self.OBJS_LIST is None or user_type == "superuser"
                    else n_objects == self.OBJS_LIST
                )
                assert (expected_with_permission) if has_permission else (n_objects < 10), (
                    f"Incorrect number of objects user `{user_type}` "
                    f"should be able to fetch from endpoint: {n_objects}."
                )

        # GET: Check permissions to who can fetch an object details
        # ---------------------------------------------------------------------

        for user_type, user in users.items():
            with AppTestClient(locals(), user=user) as tc:
                has_permission = self.PERMISSIONS[user_type][0]
                response = tc.get(
                    f"{self.endpoint}{objs[0].id}",
                    query_params={"as_superuser": True},
                    expected_codes=self.CODES_BY_PERMISSION[has_permission],
                    max_queries=self.QUERIES_GET,
                )
                if has_permission:
                    obj_data = response.data  # Use this data to put
                    assert obj_data.get("id") == str(
                        objs[0].id
                    ), "obj.id does not match with the fetched object details."

        # PATCH: Check permissions to who can patch an object
        # ---------------------------------------------------------------------

        for user_type, user in users.items():
            with AppTestClient(locals(), user=user) as tc:
                has_permission = self.PERMISSIONS[user_type][1]
                response = tc.patch(
                    f"{self.endpoint}{objs[0].id}/",
                    data={"id": objs[0].id},
                    expected_codes=self.CODES_BY_PERMISSION[has_permission],
                    max_queries=self.QUERIES_UPDATE,
                )
                if has_permission:
                    assert response.data.get("id") == str(
                        objs[0].id
                    ), "obj.id does not match with patched object."

        # UPDATE: Check permissions to who can update an object
        # ---------------------------------------------------------------------

        for user_type, user in users.items():
            with AppTestClient(locals(), user=user) as tc:
                has_permission = self.PERMISSIONS[user_type][1]
                response = tc.put(
                    f"{self.endpoint}{objs[0].id}/",
                    data=self._clean_data(obj_data),
                    expected_codes=self.CODES_BY_PERMISSION[has_permission],
                    max_queries=self.QUERIES_UPDATE,
                )
                if has_permission:
                    assert response.data.get("id") == str(
                        objs[0].id
                    ), "obj.id does not match with the updated object."

        # DELETE: Check permissions to who can delete an object
        # ---------------------------------------------------------------------

        for user_type, user in users.items():
            # Current creator is only for the obj[0]
            # Since we are deleting other objects, the creator
            # correspond the object we are about to delete
            obj = objs[existing_objects - 1]
            if user_type == "creator":
                user = obj.get_creator()

            with AppTestClient(locals(), user=user) as tc:
                has_permission = self.PERMISSIONS[user_type][3]
                response = tc.delete(
                    f"{self.endpoint}{obj.id}/",
                    expected_codes=self.CODES_BY_PERMISSION[has_permission],
                    max_queries=self.QUERIES_DELETE or 30,
                )
                if has_permission:
                    existing_objects -= 1

        # CREATE: Check permissions to who can create an object
        # ---------------------------------------------------------------------

        obj = objs[existing_objects - 1]
        obj_data = None

        for user_type, user in users.items():
            if not obj_data:
                obj_data = self._clean_data(obj.get_serializer().data)
                obj.delete()

            with AppTestClient(locals(), user=user) as tc:
                has_permission = self.PERMISSIONS[user_type][2]
                response = tc.post(
                    f"{self.endpoint}",
                    data=obj_data,
                    expected_codes=self.CODES_BY_PERMISSION[has_permission],
                    max_queries=self.QUERIES_CREATE,
                )
                if has_permission:
                    obj = self.model.objects.get(id=response.data.get("id"))
                    obj_data = None
