# Generated by Django 6.0.3 on 2026-04-20 09:37

import app.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logintoken",
            name="token",
            field=app.utils.fields.CharField(max_length=2048, unique=True),
        ),
    ]
