# Generated by Django 6.0.4 on 2026-04-27 21:50

import app.utils.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="birthdate",
        ),
        migrations.RemoveField(
            model_name="user",
            name="country",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="user",
            name="tax_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="vat",
        ),
        migrations.AddField(
            model_name="user",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=14),
        ),
        migrations.AddField(
            model_name="user",
            name="currency",
            field=app.utils.fields.CharField(blank=True, default="EUR", max_length=3),
        ),
        migrations.AddField(
            model_name="user",
            name="iban",
            field=app.utils.fields.CharField(blank=True, default="", max_length=34),
        ),
    ]
