# Generated by Django 6.0.4 on 2026-06-25 09:21

import app.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_address_remove_user_birthdate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=app.utils.fields.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="user",
            name="birthdate",
            field=app.utils.fields.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="user",
            name="onboarding_complete",
            field=app.utils.fields.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="onboarding_request_id",
            field=app.utils.fields.CharField(blank=True, default="", max_length=64),
        ),
    ]
