# Generated by Django 6.0.4 on 2026-06-25 21:41

import app.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_mark_existing_accounts_onboarded"),
    ]

    operations = [
        migrations.AddField(
            model_name="logintoken",
            name="profile_type",
            field=app.utils.fields.CharField(
                choices=[("person", "Personal"), ("business", "Business")],
                default="person",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_type",
            field=app.utils.fields.CharField(
                choices=[("person", "Personal"), ("business", "Business")],
                db_index=True,
                default="person",
                max_length=16,
            ),
        ),
    ]
