# Generated by Django 6.0.4 on 2026-06-29 14:23

import app.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_logintoken_profile_type_user_profile_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="disposable_income_band",
            field=app.utils.fields.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="user",
            name="gambling_harm",
            field=app.utils.fields.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="source_of_funds",
            field=app.utils.fields.CharField(blank=True, default="", max_length=255),
        ),
    ]
