# Generated by Django 6.0.4 on 2026-04-27 21:50

import app.core.users.utils
import app.mixins.models
import app.utils.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Movement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", app.utils.fields.CharField(default="EUR", max_length=3)),
                (
                    "counterparty_name",
                    app.utils.fields.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "counterparty_iban",
                    app.utils.fields.CharField(blank=True, default="", max_length=34),
                ),
                ("reference", app.utils.fields.CharField(blank=True, default="", max_length=255)),
                (
                    "type",
                    app.utils.fields.CharField(
                        choices=[
                            ("TRANSFER", "Transfer"),
                            ("CARD_PAYMENT", "Card payment"),
                            ("INCOMING", "Incoming"),
                            ("FEE", "Fee"),
                        ],
                        default="TRANSFER",
                        max_length=16,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(app.core.users.utils.set_delete_user),
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(app.core.users.utils.set_delete_user),
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    app.utils.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
            bases=(
                app.mixins.models.BulkActionsMixin,
                app.mixins.models.PermissionsMixin,
                app.mixins.models.SubModulesMixin,
                models.Model,
            ),
        ),
    ]
