# Generated by Django 6.0.4 on 2026-04-27 23:04

import app.mixins.models
import app.utils.encoders
import app.utils.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("action", app.utils.fields.CharField(max_length=32)),
                (
                    "data",
                    app.utils.fields.EncryptedJSONField(
                        blank=True, default=dict, encoder=app.utils.encoders.JSONEncoder
                    ),
                ),
                ("success", app.utils.fields.BooleanField(default=True)),
                (
                    "permyt_request_id",
                    app.utils.fields.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "booking",
                    app.utils.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
            bases=(
                app.mixins.models.BulkActionsMixin,
                app.mixins.models.PermissionsMixin,
                app.mixins.models.SubModulesMixin,
                models.Model,
            ),
        ),
    ]
