[fcgi-program:demo_hotel_app]
socket=tcp://localhost:9015
command=/var/deployments/demo/hotel/env/bin/daphne -u /var/deployments/demo/hotel/sockets/app.%(process_num)s.sock --fd 0 settings.asgi:application
directory=/var/deployments/demo/hotel
stderr_logfile=/var/deployments/demo/hotel/logs/app.stderr.log
stdout_logfile=/var/deployments/demo/hotel/logs/app.stdout.log
autostart=true
autorestart=true
user=ubuntu
environment=HOME="/home/ubuntu",USER="ubuntu"
numprocs=2
process_name=%(program_name)s_%(process_num)s
