[program:demo_hotel_beat]
command=/var/deployments/demo/hotel/env/bin/celery -A settings beat -l INFO
directory=/var/deployments/demo/hotel
stderr_logfile=/var/deployments/demo/hotel/logs/beat.stderr.log
stdout_logfile=/var/deployments/demo/hotel/logs/beat.stdout.log
autostart=true
autorestart=true
user=ubuntu
environment=HOME="/home/ubuntu",USER="ubuntu"
