#!/bin/bash
set -e

update_app()
{
    cd /var/deployments/demo/hotel
    git pull
    source env/bin/activate
    pip install -r requirements.txt
    python manage.py migrate
    python manage.py collectstatic --noinput
    sudo supervisorctl restart demo_hotel_app:* demo_hotel_beat demo_hotel_tasks
}

update_app
