[fcgi-program:demo_luckwing_app]
socket=tcp://localhost:9020
command=/var/deployments/demo/luckwing/env/bin/daphne -u /var/deployments/demo/luckwing/sockets/app.%(process_num)s.sock --fd 0 settings.asgi:application
directory=/var/deployments/demo/luckwing
stderr_logfile=/var/deployments/demo/luckwing/logs/app.stderr.log
stdout_logfile=/var/deployments/demo/luckwing/logs/app.stdout.log
autostart=true
autorestart=true
user=ubuntu
environment=HOME="/home/ubuntu",USER="ubuntu"
numprocs=2
process_name=%(program_name)s_%(process_num)s
