# Generated by Django 6.0.4 on 2026-06-22 10:55

import app.core.users.utils
import app.mixins.models
import app.utils.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sessions", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_type",
            field=app.utils.fields.CharField(
                choices=[("person", "Person"), ("business", "Business")],
                db_index=True,
                default="person",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="logintoken",
            name="session",
            field=app.utils.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login_tokens",
                to="sessions.session",
            ),
        ),
        migrations.CreateModel(
            name="BusinessProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("legal_name", app.utils.fields.CharField(blank=True, default="", max_length=255)),
                (
                    "registration_number",
                    app.utils.fields.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("tax_id", app.utils.fields.CharField(blank=True, default="", max_length=64)),
                ("incorporation_date", app.utils.fields.DateField(blank=True, null=True)),
                ("registered_address", app.utils.fields.TextField(blank=True, default="")),
                ("country", app.utils.fields.CharField(blank=True, default="", max_length=2)),
                (
                    "structure",
                    app.utils.fields.CharField(
                        blank=True,
                        choices=[
                            ("private_corporation", "Private corporation"),
                            ("private_partnership", "Private partnership"),
                            ("public_corporation", "Public corporation"),
                            ("sole_proprietorship", "Sole proprietorship"),
                        ],
                        default="private_corporation",
                        max_length=32,
                    ),
                ),
                ("mcc", app.utils.fields.CharField(blank=True, default="", max_length=4)),
                ("website", app.utils.fields.CharField(blank=True, default="", max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(app.core.users.utils.set_delete_user),
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(app.core.users.utils.set_delete_user),
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    app.utils.fields.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_by",),
                "abstract": False,
            },
            bases=(
                app.mixins.models.BulkActionsMixin,
                app.mixins.models.PermissionsMixin,
                app.mixins.models.SubModulesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Shareholder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("first_name", app.utils.fields.CharField(blank=True, default="", max_length=128)),
                ("last_name", app.utils.fields.CharField(blank=True, default="", max_length=128)),
                ("birthdate", app.utils.fields.DateField(blank=True, null=True)),
                ("address", app.utils.fields.TextField(blank=True, default="")),
                ("country", app.utils.fields.CharField(blank=True, default="", max_length=2)),
                ("id_number", app.utils.fields.CharField(blank=True, default="", max_length=64)),
                (
                    "ownership_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("title", app.utils.fields.CharField(blank=True, default="", max_length=128)),
                ("is_representative", app.utils.fields.BooleanField(default=False)),
                ("is_director", app.utils.fields.BooleanField(default=False)),
                (
                    "business",
                    app.utils.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shareholders",
                        to="users.businessprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(app.core.users.utils.set_delete_user),
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(app.core.users.utils.set_delete_user),
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-ownership_percent",),
            },
            bases=(
                app.mixins.models.BulkActionsMixin,
                app.mixins.models.PermissionsMixin,
                app.mixins.models.SubModulesMixin,
                models.Model,
            ),
        ),
    ]
