# Generated by Django 6.0.4 on 2026-06-25 09:19

import app.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_profile_type_alter_logintoken_session_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="logintoken",
            name="profile_type",
            field=app.utils.fields.CharField(
                choices=[("person", "Person"), ("business", "Business")],
                default="person",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="citizen_card_number",
            field=app.utils.fields.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="user",
            name="passport_number",
            field=app.utils.fields.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="user",
            name="social_security_number",
            field=app.utils.fields.CharField(blank=True, default="", max_length=16),
        ),
    ]
