# Generated by Django 6.0.4 on 2026-06-25 10:44

import app.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_logintoken_profile_type_user_citizen_card_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="logintoken",
            name="error",
            field=app.utils.fields.CharField(blank=True, default="", max_length=255),
        ),
    ]
