# Generated by Django 6.0.4 on 2026-06-29 14:21

import app.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_logintoken_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="driving_licence_categories",
            field=app.utils.fields.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="user",
            name="driving_licence_disqualified",
            field=app.utils.fields.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="driving_licence_points_band",
            field=app.utils.fields.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="user",
            name="driving_licence_valid",
            field=app.utils.fields.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="identity_verified",
            field=app.utils.fields.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="right_to_work",
            field=app.utils.fields.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="right_to_work_type",
            field=app.utils.fields.CharField(blank=True, default="", max_length=64),
        ),
    ]
