# Generated by Django 6.0.4 on 2026-04-27 23:04

import app.mixins.models
import app.utils.encoders
import app.utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "session_key",
                    app.utils.fields.CharField(db_index=True, max_length=40, unique=True),
                ),
                (
                    "permyt_user_id",
                    app.utils.fields.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    app.utils.fields.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("identity_requested", "Identity requested"),
                            ("identity_filled", "Identity filled"),
                            ("payment_requested", "Payment requested"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "form_data",
                    app.utils.fields.EncryptedJSONField(
                        blank=True, default=dict, encoder=app.utils.encoders.JSONEncoder
                    ),
                ),
                ("nights", app.utils.fields.PositiveSmallIntegerField(default=1)),
                (
                    "total_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("currency", app.utils.fields.CharField(default="EUR", max_length=3)),
                (
                    "identity_request_id",
                    app.utils.fields.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "payment_request_id",
                    app.utils.fields.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                (
                    "payment_reference",
                    app.utils.fields.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "failure_reason",
                    app.utils.fields.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "ordering": ("-created_by",),
                "abstract": False,
            },
            bases=(
                app.mixins.models.BulkActionsMixin,
                app.mixins.models.PermissionsMixin,
                app.mixins.models.SubModulesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="LoginToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("token", app.utils.fields.CharField(max_length=2048, unique=True)),
                ("scanned", app.utils.fields.BooleanField(default=False)),
            ],
            options={
                "ordering": ("-created_by",),
                "abstract": False,
            },
            bases=(
                app.mixins.models.BulkActionsMixin,
                app.mixins.models.PermissionsMixin,
                app.mixins.models.SubModulesMixin,
                models.Model,
            ),
        ),
    ]
