[fcgi-program:demo_company_app]
socket=tcp://localhost:9017
command=/var/deployments/demo/company/env/bin/daphne -u /var/deployments/demo/company/sockets/app.%(process_num)s.sock --fd 0 settings.asgi:application
directory=/var/deployments/demo/company
stderr_logfile=/var/deployments/demo/company/logs/app.stderr.log
stdout_logfile=/var/deployments/demo/company/logs/app.stdout.log
autostart=true
autorestart=true
user=ubuntu
environment=HOME="/home/ubuntu",USER="ubuntu"
numprocs=2
process_name=%(program_name)s_%(process_num)s
