[program:demo_company_beat]
command=/var/deployments/demo/company/env/bin/celery -A settings beat -l INFO
directory=/var/deployments/demo/company
stderr_logfile=/var/deployments/demo/company/logs/beat.stderr.log
stdout_logfile=/var/deployments/demo/company/logs/beat.stdout.log
autostart=true
autorestart=true
user=ubuntu
environment=HOME="/home/ubuntu",USER="ubuntu"
