[program:demo_company_tasks]
command=/var/deployments/demo/company/.venv/bin/celery -A settings worker -n demo-company@%%h -l INFO --autoscale=10,3
directory=/var/deployments/demo/company
stderr_logfile=/var/deployments/demo/company/logs/tasks.stderr.log
stdout_logfile=/var/deployments/demo/company/logs/tasks.stdout.log
autostart=true
autorestart=true
user=ubuntu
environment=HOME="/home/ubuntu",USER="ubuntu"
