#!/bin/bash
set -e

update_app()
{
    cd /var/deployments/demo/company
    git pull
    source env/bin/activate
    pip install -r requirements.txt
    python manage.py migrate
    python manage.py update_scope
    python manage.py collectstatic --no-input
    sudo supervisorctl restart demo_company_app:* demo_company_beat demo_company_tasks
}

update_app
