[pytest]
minversion = 3.10
DJANGO_SETTINGS_MODULE = settings.test
testpaths = app
norecursedirs =
    __pycache__
    migrations
    *.bk
python_files =
    test_*.py
    tests.py
addopts =
    -v -p no:warnings
    --ignore=src
    --durations=0
    --migrations
markers =
    permissions: tests that check permissions for several users.
    viewsets: tests that check viewset permissions for several users.
    code: test that checks if code structure, syntax and linting are correct.
