[fcgi-program:demo_provider_app]
socket=tcp://localhost:9011
command=/var/deployments/demo/provider/env/bin/daphne -u /var/deployments/demo/provider/sockets/app.%(process_num)s.sock --fd 0 settings.asgi:application
directory=/var/deployments/demo/provider
stderr_logfile=/var/deployments/demo/provider/logs/app.stderr.log
stdout_logfile=/var/deployments/demo/provider/logs/app.stdout.log
autostart=true
autorestart=true
user=ubuntu
environment=HOME="/home/ubuntu",USER="ubuntu"
numprocs=2
process_name=%(program_name)s_%(process_num)s
