[program:demo_provider_tasks]
command=/var/deployments/demo/provider/.venv/bin/celery -A settings worker -n demo-provider@%%h -l INFO --autoscale=10,3
directory=/var/deployments/demo/provider
stderr_logfile=/var/deployments/demo/provider/logs/tasks.stderr.log
stdout_logfile=/var/deployments/demo/provider/logs/tasks.stdout.log
autostart=true
autorestart=true
user=ubuntu
environment=HOME="/home/ubuntu",USER="ubuntu"
