#!/bin/bash
set -e

update_app()
{
    cd /var/deployments/demo/provider
    git pull
    source env/bin/activate
    pip install -r requirements.txt
    python manage.py migrate
    sudo supervisorctl restart all
}

restart_nginx()
{
    sudo service nginx restart
}

update_app
restart_nginx
