[fcgi-program:demo_government_app]
socket=tcp://localhost:9012
command=/var/deployments/demo/government/.venv/bin/daphne -u /var/deployments/demo/government/sockets/app.%(process_num)s.sock --fd 0 settings.asgi:application
directory=/var/deployments/demo/government
stderr_logfile=/var/deployments/demo/government/logs/app.stderr.log
stdout_logfile=/var/deployments/demo/government/logs/app.stdout.log
autostart=true
autorestart=true
user=ubuntu
environment=HOME="/home/ubuntu",USER="ubuntu"
numprocs=2
process_name=%(program_name)s_%(process_num)s
