#!/bin/bash
set -e

update_app()
{
    cd /var/deployments/demo/government
    git pull
    source env/bin/activate
    pip install -r requirements.txt
    python manage.py migrate
    python manage.py update_scope
    python manage.py collectstatic --no-input
    sudo supervisorctl restart demo_government_app:* demo_government_beat demo_government_tasks
}

update_app
