[program:demo_requester_beat]
command=/var/deployments/demo/requester/.venv/bin/celery -A settings beat -l INFO
directory=/var/deployments/demo/requester
stderr_logfile=/var/deployments/demo/requester/logs/beat.stderr.log
stdout_logfile=/var/deployments/demo/requester/logs/beat.stdout.log
autostart=true
autorestart=true
user=ubuntu
environment=HOME="/home/ubuntu",USER="ubuntu"
