[program:demo_requester_tasks]
command=/var/deployments/demo/requester/env/bin/celery -A settings worker -n demo-requester@%%h -l INFO --autoscale=10,3
directory=/var/deployments/demo/requester
stderr_logfile=/var/deployments/demo/requester/logs/tasks.stderr.log
stdout_logfile=/var/deployments/demo/requester/logs/tasks.stdout.log
autostart=true
autorestart=true
user=ubuntu
environment=HOME="/home/ubuntu",USER="ubuntu"
