# Generated by Django 6.0.3 on 2026-04-17 21:03

import app.core.users.utils
import app.mixins.models
import app.utils.encoders
import app.utils.fields
import django.db.models.deletion
import secured_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Nonce",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("value", app.utils.fields.CharField(db_index=True, max_length=128, unique=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(app.core.users.utils.set_delete_user),
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(app.core.users.utils.set_delete_user),
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_by",),
                "abstract": False,
            },
            bases=(
                app.mixins.models.BulkActionsMixin,
                app.mixins.models.PermissionsMixin,
                app.mixins.models.SubModulesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="RequestToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("jti", app.utils.fields.CharField(db_index=True, max_length=256, unique=True)),
                ("request_id", app.utils.fields.UUIDField()),
                ("service_id", app.utils.fields.UUIDField()),
                ("service_public_key", secured_fields.fields.EncryptedTextField()),
                (
                    "scope",
                    app.utils.fields.EncryptedJSONField(
                        blank=True, default=dict, encoder=app.utils.encoders.JSONEncoder
                    ),
                ),
                ("expires_at", app.utils.fields.DateTimeField()),
                ("used", app.utils.fields.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(app.core.users.utils.set_delete_user),
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(app.core.users.utils.set_delete_user),
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    app.utils.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
            bases=(
                app.mixins.models.BulkActionsMixin,
                app.mixins.models.PermissionsMixin,
                app.mixins.models.SubModulesMixin,
                models.Model,
            ),
        ),
    ]
