[fcgi-program:demo_vaulton_app]
socket=tcp://localhost:9019
command=/var/deployments/demo/vaulton/.venv/bin/daphne -u /var/deployments/demo/vaulton/sockets/app.%(process_num)s.sock --fd 0 settings.asgi:application
directory=/var/deployments/demo/vaulton
stderr_logfile=/var/deployments/demo/vaulton/logs/app.stderr.log
stdout_logfile=/var/deployments/demo/vaulton/logs/app.stdout.log
autostart=true
autorestart=true
user=ubuntu
environment=HOME="/home/ubuntu",USER="ubuntu"
numprocs=2
process_name=%(program_name)s_%(process_num)s
