[program:demo_vaulton_beat]
command=/var/deployments/demo/vaulton/.venv/bin/celery -A settings beat -l INFO
directory=/var/deployments/demo/vaulton
stderr_logfile=/var/deployments/demo/vaulton/logs/beat.stderr.log
stdout_logfile=/var/deployments/demo/vaulton/logs/beat.stdout.log
autostart=true
autorestart=true
user=ubuntu
environment=HOME="/home/ubuntu",USER="ubuntu"
