[program:demo_vaulton_tasks]
command=/var/deployments/demo/vaulton/env/bin/celery -A settings worker -n demo-vaulton@%%h -l INFO --autoscale=10,3
directory=/var/deployments/demo/vaulton
stderr_logfile=/var/deployments/demo/vaulton/logs/tasks.stderr.log
stdout_logfile=/var/deployments/demo/vaulton/logs/tasks.stdout.log
autostart=true
autorestart=true
user=ubuntu
environment=HOME="/home/ubuntu",USER="ubuntu"
