#!/bin/bash
set -e

update_app()
{
    cd /var/deployments/demo/vaulton
    git pull
    source env/bin/activate
    pip install -r requirements.txt
    python manage.py migrate
    python manage.py collectstatic --noinput
    sudo supervisorctl restart demo_vaulton_app:* demo_vaulton_beat demo_vaulton_tasks
}

update_app
