# Generated by Django 6.0.4 on 2026-04-27 23:04

import app.mixins.models
import app.utils.encoders
import app.utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TstMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "data",
                    app.utils.fields.JSONField(
                        blank=True, default=dict, encoder=app.utils.encoders.JSONEncoder
                    ),
                ),
                ("message", app.utils.fields.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(
                app.mixins.models.BulkActionsMixin,
                app.mixins.models.PermissionsMixin,
                app.mixins.models.SubModulesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="TstModelA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "data",
                    app.utils.fields.JSONField(
                        blank=True, default=dict, encoder=app.utils.encoders.JSONEncoder
                    ),
                ),
                ("message", app.utils.fields.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(
                app.mixins.models.BulkActionsMixin,
                app.mixins.models.PermissionsMixin,
                app.mixins.models.SubModulesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="TstModelB",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "data",
                    app.utils.fields.JSONField(
                        blank=True, default=dict, encoder=app.utils.encoders.JSONEncoder
                    ),
                ),
                ("message", app.utils.fields.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(
                app.mixins.models.BulkActionsMixin,
                app.mixins.models.PermissionsMixin,
                app.mixins.models.SubModulesMixin,
                models.Model,
            ),
        ),
    ]
