# Generated by Django 6.0.4 on 2026-06-22 11:05

import app.core.users.utils
import app.mixins.models
import app.utils.encoders
import app.utils.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sessions", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="birthdate",
        ),
        migrations.RemoveField(
            model_name="user",
            name="country",
        ),
        migrations.RemoveField(
            model_name="user",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="user",
            name="tax_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="vat",
        ),
        migrations.AlterField(
            model_name="logintoken",
            name="session",
            field=app.utils.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login_tokens",
                to="sessions.session",
            ),
        ),
        migrations.CreateModel(
            name="CompanyKB",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", app.utils.fields.CharField(blank=True, default="", max_length=255)),
                ("business_plan", app.utils.fields.TextField(blank=True, default="")),
                ("financials_summary", app.utils.fields.TextField(blank=True, default="")),
                (
                    "products",
                    app.utils.fields.JSONField(
                        blank=True, default=list, encoder=app.utils.encoders.JSONEncoder
                    ),
                ),
                ("narrative", app.utils.fields.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(app.core.users.utils.set_delete_user),
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(app.core.users.utils.set_delete_user),
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    app.utils.fields.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_kb",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_by",),
                "abstract": False,
            },
            bases=(
                app.mixins.models.BulkActionsMixin,
                app.mixins.models.PermissionsMixin,
                app.mixins.models.SubModulesMixin,
                models.Model,
            ),
        ),
    ]
