# Generated by Django 6.0.4 on 2026-06-25 12:24

import app.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_address_remove_user_birthdate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companykb",
            name="country",
            field=app.utils.fields.CharField(blank=True, default="", max_length=2),
        ),
        migrations.AddField(
            model_name="companykb",
            name="registered_address",
            field=app.utils.fields.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="companykb",
            name="registration_number",
            field=app.utils.fields.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="user",
            name="onboarding_complete",
            field=app.utils.fields.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="onboarding_request_id",
            field=app.utils.fields.CharField(blank=True, default="", max_length=64),
        ),
    ]
